# Generated by Django 2.2.3 on 2019-07-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteEM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Retorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='pword',
        ),
        migrations.AddField(
            model_name='session',
            name='password',
            field=models.CharField(default='12345', max_length=20),
        ),
    ]
